micronaut:
  application:
    name: stootistics
  router:
    static-resources:
      default:
        paths: classpath:public
        mapping: /**
        enabled: true
  http:
    client:
      event-loop-group: client
  netty:
    event-loops:
      client:
        num-threads: 12
        prefer-native-transport: true
netty:
  default:
    allocator:
      max-order: 3
